apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ktcloud-market-applications
  namespace: argocd
spec:
  generators:
    - list:
       elements:
        - app: inventory-service
          environment: release
          revision: HEAD
          ns: ktcloud-market-msa-release
        - app: order-service
          environment: release
          revision: HEAD
          ns: ktcloud-market-msa-release
        - app: product-service
          environment: release
          revision: HEAD
          ns: ktcloud-market-msa-release
        - app: user-api-gateway
          environment: release
          revision: HEAD
          ns: ktcloud-market-msa-release
  template:
    metadata:
      name: '{{ app }}-{{ environment }}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/kanei0415/ktcloud-market-msa-manifest.git
          targetRevision: HEAD
          path: '.'
          ref: template
        - repoURL: 'https://github.com/kanei0415/ktcloud-market-msa-manifest-values.git'
          targetRevision: '{{ revision }}'
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ ns }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      helm:
        valueFiles:
          - '$values/{{ app }}/values-{{ environment }}.yaml'