
nfs-subdir-external-provisioner:
  nfs:
    server: 192.168.241.158
    path: /srv/nfs/kubedata
    mountOptions:
      - nfsvers=4.1
  
  storageClass:
    name: nfs-client
    defaultClass: true
    reclaimPolicy: Delete
    archiveOnDelete: true

  volumeMounts:
    - name: nfs-subdir-external-provisioner-root
      mountPath: /persistentvolumes
  
  volumes:
    - name: nfs-subdir-external-provisioner-root
      nfs:
        server: 192.168.241.153
        path: /srv/nfs/kubedata