apiVersion: v2
name: jenkins-wrapper
description: A Helm chart for Jenkins with custom configurations
type: application
version: 1.0.0
appVersion: "2.555.1"
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"

dependencies:
  - name: jenkins
    version: "5.9.18"
    repository: "https://charts.jenkins.io"