apiVersion: v2
name: vault-wrapper
description: A Helm chart for Vault with custom configurations
type: application
version: 1.0.0
appVersion: "1.21.2"
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"

dependencies:
  - name: vault
    version: "0.32.0"
    repository: "https://helm.releases.hashicorp.com"