apiVersion: v2
name: metallb-wrapper
description: A Helm chart for MetalLB with custom configurations
type: application
version: 1.0.0
appVersion: "0.14.9"
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"

dependencies:
  - name: metallb
    version: "0.14.9"
    repository: "https://metallb.github.io/metallb"