apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-app
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - path: Addons/Postgresql
        appname: postgresql
        ns: postgresql
      - path: Addons/Redis
        appname: redis
        ns: redis
      - path: Addons/Kafka
        appname: kafka
        ns: kafka
  template:
    metadata:
      name: '{{appname}}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/kanei0415/ktcloud-local-argocd-manifest.git"
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ns}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true