apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: charts-app
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - path: Charts/MetalLB
        appname: metallb
        ns: metallb-system
      - path: Charts/Traefik
        appname: traefik
        ns: traefik
      - path: Charts/NFSProvisioner
        appname: nfs-provisioner
        ns: kube-system
  template:
    metadata:
      name: '{{appname}}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/kanei0415/ktcloud-local-argocd-manifest.git"
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ns}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true