global:
  imagePullSecrets: []
  defaultStorageClass: "nfs-client"
  storageClass: "nfs-client"

redis:
  image:
  registry: registry-1.docker.io
  repository: bitnami/redis
  tag: latest
  
  auth:
    password: "admin1234"